---
strict: true
site_name: mappers
site_description: |
  Declarative mappers from ORM models to domain entities. And back
  again!
theme:
  name: "material"
  palette:
    primary: "white"
    accent: "light-blue"
  logo: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.png"
  favicon: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.ico"
  language: "en"
repo_name: dry-python/mappers
repo_url: "https://github.com/dry-python/mappers"
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - "Home": index.md
  - "Changelog": changelog.md
  - "Development": development.md
  # A UI hack to split Table of Content into two visual parts.
  - "": "/"
  - "": "/"
  - "": "/"
  - "": "/"
  - "": "/"
  - "GitHub": "https://github.com/dry-python"
  - "Twitter": "https://twitter.com/dry_py"
  - "Gitter": "https://gitter.im/dry-python/mappers"
  - "LinkedIn": "https://www.linkedin.com/company/drylabs/"
